global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: "simulator"
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]
  - job_name: "auth"
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ["host.docker.internal:4000"]
  - job_name: "node"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "host.docker.internal:9100"
          - "host.docker.internal:9101"
          - "host.docker.internal:9102"
          - "host.docker.internal:9103"
